#defaul configuration
#using dev environment
spring:
  profiles:
    active: dev
# datasource configuration
# using mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo
    username: root
    password: root
# jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

